[vm_para_monitorar]
# O Ansible agora conecta-se ao localhost em portas diferentes
servidor-zabbix ansible_host=127.0.0.1 ansible_port=2211 ansible_user=root
host-gerido-1   ansible_host=127.0.0.1 ansible_port=2212 ansible_user=root

[vm_para_monitorar:vars]
ansible_python_interpreter=/usr/bin/python3
